version: '3'
services:
  web:
    container_name: 'flask_docker_container'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FLASK_RUN_PORT: ${FLASK_RUN_PORT}
        FLASK_RUN_HOST: ${FLASK_RUN_HOST}
    restart: always
    env_file:
      - .env
      - .flaskenv
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: ${FLASK_APP}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}

    volumes:
      - .:/usr/src/app
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    expose:
      - ${FLASK_RUN_PORT}
